// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NET105_Tutorial_Csharp5_Dungna29.DBContextFpoly;

namespace NET105_Tutorial_Csharp5_Dungna29.Migrations
{
    [DbContext(typeof(DBContextFPOLY))]
    [Migration("20210512150102_AddTableCountryV12")]
    partial class AddTableCountryV12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Color", b =>
                {
                    b.Property<int>("ColortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ColortId");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade1", b =>
                {
                    b.Property<int>("Grade1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Grade1Id");

                    b.ToTable("Grade1s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade2", b =>
                {
                    b.Property<int>("Grade2Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Grade2Id");

                    b.ToTable("Grade2s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade3", b =>
                {
                    b.Property<int>("Grade3Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Grade3Id");

                    b.ToTable("Grade3s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade4", b =>
                {
                    b.Property<int>("Grade4Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Grade4Id");

                    b.ToTable("Grade4s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Grade1Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Grade1Id");

                    b.ToTable("Student1s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student2", b =>
                {
                    b.Property<int>("Student2Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Grade2Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student2Id");

                    b.HasIndex("Grade2Id");

                    b.ToTable("Student2s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Grade3Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Grade3Id");

                    b.ToTable("Student3s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Grade4Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Grade4Id");

                    b.ToTable("Student4s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.StudentAddress", b =>
                {
                    b.Property<int>("StudentAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentAddressId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentAddress");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Country", b =>
                {
                    b.Property<int>("CountrytId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountrytId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("Money");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ColorId");

                    b.HasIndex("CountryID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student1", b =>
                {
                    b.HasOne("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade1", "Grade1")
                        .WithMany()
                        .HasForeignKey("Grade1Id");

                    b.Navigation("Grade1");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student2", b =>
                {
                    b.HasOne("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade2", null)
                        .WithMany("Student2s")
                        .HasForeignKey("Grade2Id");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student3", b =>
                {
                    b.HasOne("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade3", "Grade3")
                        .WithMany("Student3s")
                        .HasForeignKey("Grade3Id");

                    b.Navigation("Grade3");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student4", b =>
                {
                    b.HasOne("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade4", "Grade4")
                        .WithMany("Student4s")
                        .HasForeignKey("Grade4Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade4");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.StudentAddress", b =>
                {
                    b.HasOne("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student", "Student")
                        .WithOne("Address")
                        .HasForeignKey("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.StudentAddress", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Product", b =>
                {
                    b.HasOne("NET105_Tutorial_Csharp5_Dungna29.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("NET105_Tutorial_Csharp5_Dungna29.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NET105_Tutorial_Csharp5_Dungna29.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID");

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.User", b =>
                {
                    b.HasOne("NET105_Tutorial_Csharp5_Dungna29.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade2", b =>
                {
                    b.Navigation("Student2s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade3", b =>
                {
                    b.Navigation("Student3s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Grade4", b =>
                {
                    b.Navigation("Student4s");
                });

            modelBuilder.Entity("NET105_Tutorial_Csharp5_Dungna29.Models.Convention.Student", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
